name: Deploy CronBot

on:
  push:
    branches: [ main ]
    paths:
      - "src/cronbot/**"
      - "pyproject.toml"
      - "uv.lock"
      - "scripts/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout (shallow)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare SSH
        env:
          HOST: ${{ secrets.DEPLOY_HOST }}
          PORT: ${{ secrets.DEPLOY_PORT }}
        run: |
          install -m 700 -d ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -T 10 -p "$PORT" -H -t rsa,ecdsa,ed25519 "$HOST" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy over SSH (run repo script)
        env:
          HOST: ${{ secrets.DEPLOY_HOST }}
          PORT: ${{ secrets.DEPLOY_PORT }}
          USER: ${{ secrets.DEPLOY_USER }}
        run: |
          ssh -i ~/.ssh/deploy_key -p "$PORT" "$USER@$HOST" 'bash -seuo pipefail' < scripts/deploy.sh
